SiLeBAT/mibi-parse-cloud

.editorconfig
.eslintrc.cjs
.gitignore
.husky/pre-commit
.prettierrc
package-lock.json
package.json
tsconfig.json

Add linting

---

.eslintrc.cjs
.husky/pre-commit
package-lock.json
package.json
src/main.ts
src/modules/shared/domain/valueObjects/index.ts
src/modules/shared/domain/valueObjects/value-object.ts
src/modules/shared/mappers/index.ts
src/modules/shared/mappers/mapper.ts
src/modules/shared/useCases/index.ts
src/modules/shared/useCases/use-case.error.ts
src/modules/shared/useCases/use-case.ts
src/modules/system-monitoring/domain/email.vo.ts
src/modules/system-monitoring/domain/index.ts
src/modules/system-monitoring/domain/semantic-version.vo.ts
src/modules/system-monitoring/domain/system-information.vo.ts
src/modules/system-monitoring/index.ts
src/modules/system-monitoring/infrastructure/providers/configuration.provider.ts
src/modules/system-monitoring/infrastructure/providers/index.ts
src/modules/system-monitoring/infrastructure/providers/package-information.provider.ts
src/modules/system-monitoring/infrastructure/providers/provider.error.ts
src/modules/system-monitoring/mappers/index.ts
src/modules/system-monitoring/mappers/system-information-dto-mapper.ts
src/modules/system-monitoring/useCases/getSystemInformation/get-system-information.controller.ts
src/modules/system-monitoring/useCases/getSystemInformation/get-system-information.dto.ts
src/modules/system-monitoring/useCases/getSystemInformation/get-system-information.use-case.ts
src/modules/system-monitoring/useCases/getSystemInformation/index.ts
tsconfig.json

- Add shared classes
Ticket: mps#399

Add Get System Information use case

---

.gitignore
.husky/pre-commit
package-lock.json
package.json
src/main.ts
src/modules/catalogue-management/domain/catalogue.entity.ts
src/modules/catalogue-management/domain/enums.ts
src/modules/catalogue-management/domain/file-content.vo.ts
src/modules/catalogue-management/domain/index.ts
src/modules/catalogue-management/index.ts
src/modules/catalogue-management/infrastructure/parse-types.ts
src/modules/catalogue-management/legacy/avv-catalogue-parser.ts
src/modules/catalogue-management/legacy/index.ts
src/modules/catalogue-management/legacy/xml-catalog.model.ts
src/modules/catalogue-management/mappers/catalogue-to-persistence.mapper.ts
src/modules/catalogue-management/mappers/index.ts
src/modules/catalogue-management/useCases/createAVVCatalogue/create-avv-catalogue.error.ts
src/modules/catalogue-management/useCases/createAVVCatalogue/create-avv-catalogue.hook.ts
src/modules/catalogue-management/useCases/createAVVCatalogue/create-avv-catalogue.use-case.ts
src/modules/catalogue-management/useCases/createAVVCatalogue/index.ts
src/modules/catalogue-management/useCases/deleteAVVCatalogue/delete-avv-catalogue.hook.ts
src/modules/catalogue-management/useCases/deleteAVVCatalogue/index.ts
src/modules/shared/domain/entities/entity.ts
src/modules/shared/domain/entities/index.ts
src/modules/shared/domain/valueObjects/entity-id.vo.ts
src/modules/shared/domain/valueObjects/index.ts
src/modules/shared/infrastructure/index.ts
src/modules/shared/infrastructure/types.ts
src/modules/system-monitoring/index.ts
src/modules/system-monitoring/useCases/getSystemInformation/index.ts

Add Create AVV Catalogue Use Case

---

src/modules/system-update/integrity-functions/index.ts
src/modules/system-update/integrity-functions/mp26-check-user-info-link.ts
src/modules/system-update/useCases/checkReferentialIntegrity/check-referential-integrity.use-case.ts
src/modules/system-update/useCases/checkReferentialIntegrity/index.ts
src/modules/system-update/useCases/index.ts

Add Integrity check for User_Info collection

---

src/modules/system-update/migration-functions/mp35-create-user-info.ts
src/modules/system-update/schemas/User_Info.json

Add CLP to User_Info Schema

---

src/modules/system-update/integrity-functions/mp26-check-user-info-link.ts
src/modules/system-update/migration-functions/create-schema.ts
src/modules/system-update/migration-functions/index.ts
src/modules/system-update/migration-functions/mp37-create-avv-catalogue.ts
src/modules/system-update/schemas/AVV_Catalogue.json

Add AVV_Catalogue Schema creation

---

src/modules/system-update/migration-functions/index.ts
src/modules/system-update/migration-functions/mp41-create-template-file.ts
src/modules/system-update/schemas/Template_File.json

Add Template_File Schema creation

---

src/modules/system-update/migration-functions/index.ts
src/modules/system-update/migration-functions/mp40-create-analysis-procedure.ts
src/modules/system-update/schemas/Analysis_Procedure.json

Add Analysis Procedure Schema creation

---

src/modules/system-update/migration-functions/index.ts
src/modules/system-update/migration-functions/mp38-create-additional-pathogens.ts
src/modules/system-update/schemas/Additional_Pathogens.json

Add Additional_Pathogens Scheam creation

---

src/modules/system-update/migration-functions/index.ts
src/modules/system-update/migration-functions/mp39-create-nrl.ts
src/modules/system-update/schemas/NRL.json

Add NRL Schema creation

---

src/modules/validation/useCases/validateSubmission/validate-submission.controller.ts

Refactor validation controller response

---

src/modules/catalogue-management/legacy/avv-catalogue-parser.ts

Ticket: https://app.zenhub.com/workspaces/mibi-portal-5a817089b72527484e410a5a/issues/gh/silebat/mibi-portal-client/610

Adjusted catalog parsing for hierarchy codes and obligatory facetten.

---

src/modules/validation/legacy/application/custom-auto-correction-functions.ts
src/modules/validation/legacy/model/avvcatalog.entity.ts
src/modules/validation/legacy/model/custom-validator-functions.ts
src/modules/validation/legacy/model/legacy.model.ts
src/modules/validation/legacy/model/validation-constraints.ts
src/modules/validation/legacy/model/validator.entity.ts
src/modules/validation/legacy/repositories/avvcatalog.repository.ts

Ticket: https://app.zenhub.com/workspaces/mibi-portal-5a817089b72527484e410a5a/issues/gh/silebat/mibi-parse-cloud/30
Ticket: https://app.zenhub.com/workspaces/mibi-portal-5a817089b72527484e410a5a/issues/gh/silebat/mibi-parse-cloud/54

Add remaining validation code.

---

src/modules/validation/legacy/model/custom-validator-functions.ts
src/modules/validation/legacy/model/validation-constraints.ts
src/modules/validation/legacy/model/validator.entity.ts

Ticket: https://app.zenhub.com/workspaces/mibi-portal-5a817089b72527484e410a5a/issues/gh/silebat/mibi-parse-cloud/61

Add check whether multiple facettes are allowed

---

src/modules/system-update/migration-functions/index.ts
src/modules/system-update/migration-functions/mp66-update-user-info.ts
src/modules/system-update/migration-functions/update-schema.ts

Update User_Info collection to include first name, last name and email

---

src/modules/system-update/migration-functions/create-schema.ts
src/modules/system-update/migration-functions/mp66-update-user-info.ts
src/modules/system-update/migration-functions/update-schema.ts

Add guard function to update schema function

---

src/modules/orders/infrastructure/repositories/customer.repository.ts
src/modules/orders/infrastructure/repositories/index.ts
src/modules/orders/infrastructure/repositories/user.repository.ts
src/modules/orders/legacy/anti-corruption/submission.anti-corruption-layer.ts
src/modules/orders/mappers/customer-persistence.mapper.ts
src/modules/orders/useCases/create-submitter-id/create-submitter-id.use-case.ts
src/modules/orders/useCases/create-submitter-id/index.ts
src/modules/orders/useCases/create-validation-options/create-validation-options.use-case.ts
src/modules/orders/useCases/submit-order/submit-order.controller.ts
src/modules/orders/useCases/submit-order/submit-order.use-case.ts
src/modules/orders/useCases/validate-order/validate-order.controller.ts
src/modules/orders/useCases/validate-order/validate-order.use-case.ts
src/modules/system-update/schemas/User_Info.json

Receive useremail from REST request to allow user identofication

---

src/modules/orders/legacy/anti-corruption/submission.anti-corruption-layer.ts
src/modules/orders/legacy/application/mail.ts
src/modules/orders/legacy/application/views/de/adminactivation.html
src/modules/orders/legacy/application/views/de/jobnotification.html
src/modules/orders/legacy/application/views/de/pwreset.html
src/modules/orders/legacy/application/views/de/pwresethelp.html
src/modules/orders/legacy/application/views/de/regactivation.html
src/modules/orders/legacy/application/views/de/sentnotification.html
src/modules/orders/useCases/create-submitter-id/create-submitter-id.use-case.ts
src/modules/shared/domain/valueObjects/server-config.vo.ts
src/modules/shared/useCases/get-server-config/get-server-config.use-case.ts

Fix error in email retrieval for jobRecipient

---

src/modules/orders/domain/customer.entity.ts
src/modules/orders/legacy/anti-corruption/excel-unmarshal.anti-corruption-layer.ts
src/modules/orders/legacy/anti-corruption/submission.anti-corruption-layer.ts
src/modules/orders/legacy/model/custom-validator-functions.ts
src/modules/orders/useCases/create-submission-file/create-submission-file.controller.ts
src/modules/orders/useCases/parse-sample-data/parse-sample-data.controller.ts
src/modules/orders/useCases/submit-order/submit-order.controller.ts
src/modules/orders/useCases/validate-order/validate-order.controller.ts
src/modules/shared/core/controller.ts
src/modules/system-monitoring/useCases/getSystemInformation/get-system-information.controller.ts

- Ansprechpartner in Einsendebogen no longer has to be a valid name
- add controller logging helper function
Ticket: #88

Fix Validation Bug

---

src/modules/orders/legacy/anti-corruption/excel-unmarshal.anti-corruption-layer.ts
src/modules/orders/useCases/parse-sample-data/parse-from-json.use-case.ts
src/modules/orders/useCases/parse-sample-data/parse-from-xlsx.use-case.ts
src/modules/orders/useCases/parse-sample-data/parse-sample-data.controller.ts
src/modules/orders/useCases/parse-sample-data/parse-sample-data.use-case.ts

Ticket: mibi-portal-server#450

Adjust parseSampleController to allow return of XML

---

package-lock.json
package.json
src/modules/orders/infrastructure/repositories/index.ts
src/modules/shared/infrastructure/parse-types.ts
src/modules/shared/infrastructure/repositories/base.repository.ts
src/modules/system-initialise/index.ts
src/modules/system-initialise/infrastructure/repository/additional-pathogens.repository.ts
src/modules/system-initialise/infrastructure/repository/analysis-procedures.repository.ts
src/modules/system-initialise/infrastructure/repository/avv-catalog.repository.ts
src/modules/system-initialise/infrastructure/repository/index.ts
src/modules/system-initialise/infrastructure/repository/plz.repository.ts
src/modules/system-initialise/infrastructure/repository/template-file.repository.ts
src/modules/system-initialise/infrastructure/repository/user-info.repository.ts
src/modules/system-initialise/useCases/checkCollectionsForContent/check-collections-for-content.use-case.ts
src/modules/system-initialise/useCases/checkCollectionsForContent/index.ts
src/modules/system-initialise/useCases/index.ts
src/modules/system-initialise/useCases/setPLZCache/set-plz-cache.use-case.ts

Add check for empty collections

---

src/modules/catalogue-management/domain/index.ts
src/modules/catalogue-management/domain/pathogen.vo.ts
src/modules/catalogue-management/infrastructure/repository/index.ts
src/modules/catalogue-management/infrastructure/repository/pathogen.repository.ts
src/modules/catalogue-management/legacy/avv-catalogue-parser.ts

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/103

Load additional pathogens from db during xml parsing

---

src/modules/orders/legacy/anti-corruption/excel-unmarshal.anti-corruption-layer.ts
src/modules/orders/legacy/anti-corruption/validation.anti-corruption-layer.ts
src/modules/orders/legacy/application/sample-sheet.service.ts
src/modules/orders/legacy/index.ts
src/modules/orders/legacy/model/legacy.model.ts

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/101

Wizard now shows text from Einsendebogen

---

src/modules/orders/legacy/model/legacy.model.ts
src/modules/orders/legacy/model/sample-sheet.strings.ts
src/modules/shared/domain/valueObjects/nrl-id.vo.ts

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/102

Shows new pathogen Klebsiella

---

src/modules/catalogue-management/legacy/avv-catalogue-parser.ts

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/108

Add duplicate check for additional pathogens

---

src/modules/orders/legacy/application/custom-auto-correction-functions.ts
src/modules/orders/legacy/application/form-auto-correction.service.ts

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/115

AVV code validation is incorrect for 1 example

---

src/modules/orders/legacy/anti-corruption/excel-marshall.anti-corruption-layer.ts
src/modules/orders/legacy/anti-corruption/submission.anti-corruption-layer.ts
src/modules/orders/legacy/anti-corruption/urgency.mapper.ts
src/modules/orders/legacy/anti-corruption/validation.anti-corruption-layer.ts

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/117

Sending an order does not work on qa

---

src/modules/orders/legacy/application/form-auto-correction.service.ts
src/modules/orders/legacy/model/sample.entity.ts

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/120

Fix autocorrection behaviour

---

src/modules/orders/use-cases/submit-order/submit-order.controller.ts

Contact email in Excel is no longer overwritten with email
address of sending User
Ticket: #78

Fix bug of overwritten contact email

---

src/modules/catalog-management/mappers/catalog-information-to-persistence.mapper.ts
src/modules/catalog-management/mappers/catalog-to-persistence.mapper.ts
src/modules/catalog-management/use-cases/uploadAVVCatalog/before-avv-catalog-save.hook.ts
src/modules/orders/infrastructure/repository/avvcatalog.repository.ts
src/modules/orders/use-cases/set-avv-catalog-cache/set-avvcatalog-cache.hook.ts
src/modules/shared/infrastructure/parse-types.ts
src/modules/system-update/migration-functions/mp37-create-avv-catalog.ts
src/modules/system-update/migration-functions/mp64-update-avv-catalog.ts
src/modules/system-update/schemas/AVV_Catalogue.json

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/127

Refactor catalogue -> catalog in DB.

---

src/modules/user-management/index.ts
src/modules/user-management/infrastructure/index.ts
src/modules/user-management/infrastructure/repositories/index.ts
src/modules/user-management/infrastructure/repositories/institute.repository.ts
src/modules/user-management/use-cases/index.ts
src/modules/user-management/use-cases/register-user/index.ts
src/modules/user-management/use-cases/register-user/register-user.hook.ts

Registering a user creates a linked entry in User_Information

---

src/modules/orders/legacy/application/custom-auto-correction-functions.ts

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/126

Autocorrection could return wrong data after uploading new 124 catalog.

---

src/modules/orders/use-cases/check-template-files/check-template-files.use-case.ts
src/modules/orders/use-cases/check-template-files/index.ts
src/modules/orders/use-cases/index.ts
src/modules/system-initialise/use-cases/checkCollectionsForContent/check-collections-for-content.use-case.ts

Add institutions collection to list of collections checked for
content
Ticket: #131

Add integrity check for presence of Template Files

---

src/modules/orders/legacy/anti-corruption/submission.anti-corruption-layer.ts
src/modules/orders/use-cases/submit-order/submit-order.use-case.ts

Fix email not showing correct submitter

---

src/modules/orders/infrastructure/repository/avvcatalog.repository.ts
src/modules/orders/mappers/acc-catalog-persistence.mapper.ts
src/modules/orders/mappers/index.ts
src/modules/orders/use-cases/check-avv-catalog-collection-completeness/check-avv-catalog-collection-completeness.use-case.ts
src/modules/orders/use-cases/check-avv-catalog-collection-completeness/index.ts
src/modules/orders/use-cases/check-template-files/index.ts
src/modules/orders/use-cases/index.ts
src/modules/system-initialise/index.ts
src/modules/system-initialise/use-cases/checkCollectionsForContent/check-collections-for-content.use-case.ts
src/modules/system-initialise/use-cases/checkCollectionsForContent/index.ts
src/modules/system-initialise/use-cases/checkSystemConfiguration/index.ts
src/modules/system-initialise/use-cases/index.ts

Add integrity check for presence of AVV Catalogs

---

src/modules/orders/use-cases/parse-sample-data/parse-sample-data.controller.ts
src/modules/shared/domain/domain.error.ts
src/modules/shared/domain/valueObjects/email-validation.error.ts
src/modules/shared/domain/valueObjects/email.vo.ts

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/140

Add warning toaster: Email address is missing

---

src/modules/system-update/integrity-functions/mp26-check-user-info-link.ts

Make email retrieval case insensitive

---

src/modules/system-update/migration-functions/index.ts
src/modules/system-update/migration-functions/mp151-create-client-dashboard.ts
src/modules/system-update/migration-functions/mp86-create-search-alias.ts
src/modules/system-update/schemas/Client_Dashboard.json

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/151

Add Dashboard option to activate alternative welcome page

---

src/modules/shared/infrastructure/cache/zomo-plan.cache.ts

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/163

Add ZoMo plan usage only for current and last year.

---

src/modules/orders/use-cases/create-submitter-id/create-submitter-id.use-case.ts
src/modules/orders/use-cases/validate-order/validate-order.controller.ts
src/modules/shared/domain/valueObjects/email.vo.ts

Amend logging for submitterId

---

src/modules/orders/domain/enums.ts
src/modules/orders/use-cases/parse-sample-data/parse-sample-data.controller.ts
src/modules/shared/domain/valueObjects/email.vo.ts

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/170

Fix Email Validation Error is not catched properly

---

src/modules/system-monitoring/use-cases/addInstitute/add-institute.error.ts
src/modules/system-monitoring/use-cases/addInstitute/before-institute-save.hook.ts
src/modules/system-monitoring/use-cases/addInstitute/index.ts
src/modules/system-monitoring/use-cases/index.ts

Ticket: https://github.com/SiLeBAT/mibi-parse-cloud/issues/149

Set required fields on institutions collection
